
# @package _global_
# problem args

problem_id: "all_high"
graph_size: 50

# cfg specifying Solomon data groups, types and tw fractions
_data_cfg:
  groups: [ "r", "c", "rc" ]
  types: [1]
  tw_fracs: [ 1.0 ]

# RPEnv cfg
env_cfg:
  k_nbh_frac: 0.32

# data
train_ds_cfg:
  cfg: ${_data_cfg}
  stats_pth: "./solomon_stats.pkl"
  data_pth: #

val_ds_cfg:
  cfg: ${_data_cfg}
  stats_pth: "./solomon_stats.pkl"
  data_pth: #

test_ds_cfg:
  cfg: ${_data_cfg}
  stats_pth: #
  data_pth: "./data/solomon_prep.pkl"
